import React, { useState } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Button,
  Grid,
  CircularProgress,
  Alert,
} from '@mui/material';
import {
  PictureAsPdf,
  Download,
  CloudDownload,
} from '@mui/icons-material';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { toast } from 'react-toastify';
import { exportAPI, subscriptionAPI, budgetAPI } from '../../services/api';
import { formatCurrency, formatDate } from '../../utils/helpers';

const ExportPdf = () => {
  const [loading, setLoading] = useState(false);
  const [loadingFrontend, setLoadingFrontend] = useState(false);

  // Backend PDF Export
  const handleBackendExport = async () => {
    try {
      setLoading(true);
      const response = await exportAPI.exportPdf();

      // Create blob and download
      const blob = new Blob([response.data], { type: 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `subscription-report-${new Date().toISOString().split('T')[0]}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      toast.success('PDF downloaded successfully!');
    } catch (error) {
      console.error('Error exporting PDF:', error);
      toast.error('Failed to export PDF');
    } finally {
      setLoading(false);
    }
  };

  // Frontend PDF Export using jsPDF
  const handleFrontendExport = async () => {
    try {
      setLoadingFrontend(true);

      // Fetch data
      const [subsResponse, budgetResponse] = await Promise.all([
        subscriptionAPI.getUserSubscriptions(),
        budgetAPI.getBudgetSummary(),
      ]);

      const subscriptions = subsResponse.data.data || [];
      const budget = budgetResponse.data.data;

      // Create PDF
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();

      // Title
      doc.setFontSize(24);
      doc.setTextColor(102, 126, 234);
      doc.text('Subscription Tracker Report', pageWidth / 2, 25, { align: 'center' });

      // Date
      doc.setFontSize(10);
      doc.setTextColor(128, 128, 128);
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, 35, { align: 'center' });

      // Summary Section
      doc.setFontSize(16);
      doc.setTextColor(0, 0, 0);
      doc.text('Budget Summary', 14, 50);

      doc.setFontSize(11);
      doc.text(`Monthly Income: ${formatCurrency(budget?.monthlyIncome || 0)}`, 14, 60);
      doc.text(`Monthly Expenses: ${formatCurrency(budget?.monthlyExpenses || 0)}`, 14, 68);
      doc.text(`Subscription Total: ${formatCurrency(budget?.subscriptionTotal || 0)}`, 14, 76);
      doc.text(`Remaining Budget: ${formatCurrency(budget?.remainingBudget || 0)}`, 14, 84);
      doc.text(`Budget Usage: ${budget?.budgetPercentageUsed?.toFixed(1) || 0}%`, 14, 92);

      // Subscriptions Table
      doc.setFontSize(16);
      doc.text('Active Subscriptions', 14, 110);

      if (subscriptions.length > 0) {
        const tableData = subscriptions.map((sub) => [
          sub.subscriptionName,
          sub.category,
          sub.subscriptionType,
          formatCurrency(sub.customPrice || sub.originalPrice),
          formatDate(sub.renewalDate),
          sub.daysUntilRenewal !== null ? `${sub.daysUntilRenewal} days` : 'N/A',
        ]);

        doc.autoTable({
          startY: 118,
          head: [['Subscription', 'Category', 'Type', 'Price', 'Renewal Date', 'Days Left']],
          body: tableData,
          theme: 'striped',
          headStyles: {
            fillColor: [102, 126, 234],
            textColor: 255,
            fontStyle: 'bold',
          },
          styles: {
            fontSize: 9,
          },
          columnStyles: {
            0: { cellWidth: 35 },
            1: { cellWidth: 25 },
            2: { cellWidth: 20 },
            3: { cellWidth: 25 },
            4: { cellWidth: 30 },
            5: { cellWidth: 20 },
          },
        });

        // Total
        const finalY = doc.lastAutoTable.finalY + 10;
        doc.setFontSize(12);
        doc.setFont(undefined, 'bold');
        doc.text(
          `Total Monthly Cost: ${formatCurrency(budget?.subscriptionTotal || 0)}`,
          14,
          finalY
        );
      } else {
        doc.setFontSize(11);
        doc.text('No active subscriptions found.', 14, 118);
      }

      // Footer
      const pageHeight = doc.internal.pageSize.getHeight();
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      doc.text(
        'Generated by Subscription Tracker',
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );

      // Save
      doc.save(`subscription-report-${new Date().toISOString().split('T')[0]}.pdf`);
      toast.success('PDF generated successfully!');

    } catch (error) {
      console.error('Error generating PDF:', error);
      toast.error('Failed to generate PDF');
    } finally {
      setLoadingFrontend(false);
    }
  };

  return (
    <Box>
      {/* Header */}
      <Box sx={{ mb: 3 }}>
        <Typography variant="h4" fontWeight={700}>
          Export Report
        </Typography>
        <Typography variant="body2" color="text.secondary">
          Download your subscription data as a PDF report
        </Typography>
      </Box>

      <Grid container spacing={3}>
        {/* Backend Export */}
        <Grid item xs={12} md={6}>
          <Card sx={{ borderRadius: 3, height: '100%' }}>
            <CardContent sx={{ textAlign: 'center', py: 6 }}>
              <CloudDownload sx={{ fontSize: 64, color: 'primary.main', mb: 2 }} />
              <Typography variant="h6" fontWeight={600} gutterBottom>
                Server-Generated PDF
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
                Download a professionally formatted PDF generated on the server with
                advanced styling and layout.
              </Typography>
              <Button
                variant="contained"
                size="large"
                startIcon={loading ? <CircularProgress size={20} color="inherit" /> : <Download />}
                onClick={handleBackendExport}
                disabled={loading}
                sx={{
                  backgroundColor: '#E50914',
                  '&:hover': { backgroundColor: '#B81D24' },
                }}
              >
                {loading ? 'Generating...' : 'Download PDF'}
              </Button>
            </CardContent>
          </Card>
        </Grid>

        {/* Frontend Export */}
        <Grid item xs={12} md={6}>
          <Card sx={{ borderRadius: 3, height: '100%' }}>
            <CardContent sx={{ textAlign: 'center', py: 6 }}>
              <PictureAsPdf sx={{ fontSize: 64, color: 'secondary.main', mb: 2 }} />
              <Typography variant="h6" fontWeight={600} gutterBottom>
                Browser-Generated PDF
              </Typography>
              <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
                Generate a PDF directly in your browser. Faster download with
                basic formatting.
              </Typography>
              <Button
                variant="outlined"
                size="large"
                startIcon={
                  loadingFrontend ? <CircularProgress size={20} color="inherit" /> : <Download />
                }
                onClick={handleFrontendExport}
                disabled={loadingFrontend}
              >
                {loadingFrontend ? 'Generating...' : 'Generate PDF'}
              </Button>
            </CardContent>
          </Card>
        </Grid>
      </Grid>

      {/* Info */}
      <Alert severity="info" sx={{ mt: 3 }}>
        <Typography variant="body2">
          <strong>Note:</strong> The PDF includes your current subscription details and budget
          summary. For the most accurate data, make sure your subscriptions and budget
          information are up to date.
        </Typography>
      </Alert>
    </Box>
  );
};

export default ExportPdf;